### ISSUE TITLE
Проект будет обновляться или решили забить?

### ISSUE THREAD

**Issue by ipl-adm** [Pishka/MineDonate#22]
Проект будет обновляться или решили забить?

**Comment by 1061911** [comment]
Что обновлять?

**Comment by ipl-adm** [comment]
Обновлять мод. Видел, что висит тодошник в репозитории и вроде как зарекались про веб обвязку.

**Comment by ghost** [comment]
Будет кому сделать веб обвязку - сделаем. А остальное - весьма второстепенно
